(()=>{
const schedule='https://mpcsdiscord-production.up.railway.app/api/schedule',liveBase='https://mpcsdiscord-production.up.railway.app/api/live/';let timer=null,current=null;
const style=document.createElement('style');style.textContent=`.watch-now{margin-left:8px;padding:8px 12px;border:1px solid #00e5ff;background:#00e5ff;color:#041014;font:900 10px var(--body);letter-spacing:1.2px;cursor:pointer}.watch-now:hover{box-shadow:0 0 22px #00e5ff66;transform:translateY(-2px)}.live-watch{position:fixed;inset:0;z-index:9999;display:none;place-items:center;padding:24px;background:#02080dcc;backdrop-filter:blur(10px)}.live-watch.open{display:grid}.live-card{width:min(900px,100%);border:1px solid #23404b;background:linear-gradient(145deg,#0d1d24,#071116);box-shadow:0 25px 100px #000;padding:28px}.live-top{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #20343d;padding-bottom:18px}.live-top b{color:#ff405c;letter-spacing:2px}.live-close{border:0;background:none;color:#fff;font-size:28px;cursor:pointer}.live-fighters{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:24px;padding:35px 0}.live-player{text-align:center}.live-player h2{margin:0 0 12px;font:900 34px var(--head)}.live-hearts{color:#ff405c;font:800 26px var(--head)}.health-track{height:10px;margin:15px auto 0;max-width:280px;background:#18272d}.health-track i{display:block;height:100%;background:linear-gradient(90deg,#ff405c,#ff735c);transition:width .25s}.live-vs{text-align:center;color:#60757e}.live-vs b{display:block;color:#fff;font-size:25px}.combat-log{max-height:230px;overflow:auto;border-top:1px solid #20343d;padding-top:16px}.combat-log p{display:flex;justify-content:space-between;margin:0;padding:10px;border-bottom:1px solid #17272e;color:#b8c5ca}.combat-log strong{color:#fff}.combat-log em{color:#ff6075;font-style:normal}@media(max-width:650px){.live-fighters{grid-template-columns:1fr}.live-vs{order:-1}.live-card{padding:18px}}`;document.head.append(style);
const modal=document.createElement('div');modal.className='live-watch';modal.innerHTML=`<section class="live-card"><div class="live-top"><div><b>● LIVE</b><h3>SWORD MATCH</h3></div><button class="live-close">×</button></div><div id="liveContent"></div></section>`;document.body.append(modal);modal.querySelector('.live-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};
function close(){modal.classList.remove('open');current=null;clearTimeout(timer)}
function open(id){current=id;modal.classList.add('open');load()}
function hearts(value){return `${Number(value).toFixed(1)} ❤`}
function render(data){const [a={name:'TBD',health:0,maxHealth:20},b={name:'TBD',health:0,maxHealth:20}]=data.players||[];const events=data.events||[];document.getElementById('liveContent').innerHTML=`<div class="live-fighters"><div class="live-player"><h2>${escape(a.name)}</h2><div class="live-hearts">${hearts(a.health)}</div><div class="health-track"><i style="width:${Math.max(0,Math.min(100,a.health/a.maxHealth*100))}%"></i></div></div><div class="live-vs"><span>ROUND ${data.round}</span><b>${data.scoreOne} — ${data.scoreTwo}</b></div><div class="live-player"><h2>${escape(b.name)}</h2><div class="live-hearts">${hearts(b.health)}</div><div class="health-track"><i style="width:${Math.max(0,Math.min(100,b.health/b.maxHealth*100))}%"></i></div></div></div><div class="combat-log"><h3>LIVE COMBAT FEED</h3>${events.length?events.map(e=>`<p><span><strong>${escape(e.attacker)}</strong> hit ${escape(e.target)}</span><span><em>-${Number(e.damage).toFixed(1)} ❤</em> · ${Number(e.remaining).toFixed(1)} left</span></p>`).join(''):'<p>Waiting for the first hit…</p>'}</div>`}
function escape(v){const d=document.createElement('div');d.textContent=String(v??'TBD');return d.innerHTML}
function load(){if(!current)return;fetch(liveBase+encodeURIComponent(current),{cache:'no-store'}).then(r=>{if(!r.ok)throw 0;return r.json()}).then(render).catch(()=>{document.getElementById('liveContent').innerHTML='<div class="empty-state"><h2>ARENA PREPARING</h2><p>The live combat feed will appear when the Sword round starts.</p></div>'}).finally(()=>{if(current)timer=setTimeout(load,750)})}
function decorate(){fetch(schedule,{cache:'no-store'}).then(r=>r.json()).then(data=>{const live=(data.matches||[]).filter(m=>m.status==='LIVE');document.querySelectorAll('#matchList .match-game').forEach(card=>{card.querySelector('.watch-now')?.remove();const text=card.textContent.toLowerCase(),match=live.find(m=>text.includes(String(m.teamOneName||'').toLowerCase())&&text.includes(String(m.teamTwoName||'').toLowerCase()));if(!match)return;const button=document.createElement('button');button.className='watch-now';button.textContent='WATCH NOW';button.onclick=()=>open(match.id);card.querySelector('.game-status')?.after(button)})}).catch(()=>{})}
decorate();setInterval(decorate,1000);
})();
