(()=>{
const endpoint='https://mpcsdiscord-production.up.railway.app/api/live',list=document.getElementById('liveGameList'),search=document.getElementById('livePlayerSearch'),count=document.getElementById('liveCount'),status=document.getElementById('liveGameStatus');if(!list)return;let games=[],current=null,viewerTimer=null;
const esc=value=>{const node=document.createElement('div');node.textContent=String(value??'Unknown');return node.innerHTML},player=(game,index)=>game.players?.[index]||{name:`Player ${index+1}`,health:0,maxHealth:20};
const modal=document.createElement('div');modal.className='live-watch';modal.innerHTML='<section class="live-card"><div class="live-top"><div><b>● LIVE</b><h3 id="liveMode">LIVE DUEL</h3></div><button class="live-close" aria-label="Close">×</button></div><div id="liveContent"></div></section>';document.body.append(modal);
function close(){current=null;clearTimeout(viewerTimer);modal.classList.remove('open')}modal.querySelector('.live-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};
function renderList(){const query=search.value.trim().toLowerCase(),filtered=games.filter(game=>game.players?.some(p=>String(p.name||'').toLowerCase().includes(query)));count.textContent=games.length;status.textContent=query?`${filtered.length} game${filtered.length===1?'':'s'} match “${search.value.trim()}”`:`${games.length} active duel${games.length===1?'':'s'} across MPCS`;list.innerHTML=filtered.length?filtered.map(game=>{const a=player(game,0),b=player(game,1);return `<article class="live-game-card"><div class="live-game-meta"><span class="live-pill">LIVE NOW</span><span>${esc(game.mode)} · ROUND ${Number(game.round)||1}</span></div><div class="live-players"><div class="live-person"><img src="https://mc-heads.net/avatar/${encodeURIComponent(a.uuid||a.name)}/64" alt=""><strong>${esc(a.name)}</strong></div><div class="live-score">SCORE<b>${Number(game.scoreOne)||0}—${Number(game.scoreTwo)||0}</b></div><div class="live-person"><img src="https://mc-heads.net/avatar/${encodeURIComponent(b.uuid||b.name)}/64" alt=""><strong>${esc(b.name)}</strong></div></div><button class="watch-live" data-id="${esc(game.matchId)}">WATCH LIVE</button></article>`}).join(''):`<div class="live-empty"><h2>${query?'NO LIVE GAME FOUND':'NO GAMES LIVE'}</h2><p>${query?'Check the IGN and try again.':'Active duels will appear here automatically.'}</p></div>`}
function eventRow(e){if(e.type==='ROUND_WIN'||e.type==='MATCH_WIN')return `<p class="round-event"><span><strong>${esc(e.winner)}</strong> won ${e.type==='MATCH_WIN'?'the match':`round ${e.round}`}</span><span>${Number(e.scoreOne)||0} — ${Number(e.scoreTwo)||0}</span></p>`;return `<p><span><strong>${esc(e.attacker)}</strong> hit ${esc(e.target)}</span><span><em>-${Number(e.damage||0).toFixed(1)} ❤</em> · ${Number(e.remaining||0).toFixed(1)} left</span></p>`}
function renderViewer(data){const a=player(data,0),b=player(data,1),pct=p=>Math.max(0,Math.min(100,Number(p.health||0)/Math.max(1,Number(p.maxHealth||20))*100));document.getElementById('liveMode').textContent=`${data.mode||'MPCS'} DUEL`;document.getElementById('liveContent').innerHTML=`<div class="live-fighters"><div class="live-player"><h2>${esc(a.name)}</h2><div class="live-hearts">${Number(a.health||0).toFixed(1)} ❤</div><div class="health-track"><i style="width:${pct(a)}%"></i></div></div><div class="live-vs"><span>ROUND ${Number(data.round)||1}</span><b>${Number(data.scoreOne)||0} — ${Number(data.scoreTwo)||0}</b></div><div class="live-player"><h2>${esc(b.name)}</h2><div class="live-hearts">${Number(b.health||0).toFixed(1)} ❤</div><div class="health-track"><i style="width:${pct(b)}%"></i></div></div></div><div class="combat-log"><h3>LIVE COMBAT FEED</h3>${data.events?.length?data.events.map(eventRow).join(''):'<p>Waiting for the first hit…</p>'}</div>`}
async function loadViewer(){if(!current)return;try{const response=await fetch(`${endpoint}/${encodeURIComponent(current)}`,{cache:'no-store'});if(!response.ok)throw Error();renderViewer(await response.json())}catch{document.getElementById('liveContent').innerHTML='<div class="live-empty"><h2>GAME ENDED</h2><p>This duel is no longer live.</p></div>'}finally{if(current)viewerTimer=setTimeout(loadViewer,750)}}function open(id){current=id;modal.classList.add('open');loadViewer()}
async function refresh(){try{const response=await fetch(endpoint,{cache:'no-store'});if(!response.ok)throw Error();games=(await response.json()).games||[];renderList()}catch{status.textContent='Live service is reconnecting…';if(!games.length)list.innerHTML='<div class="live-empty"><h2>RECONNECTING</h2><p>The live game feed will be back shortly.</p></div>'}}
list.onclick=e=>{const button=e.target.closest('.watch-live');if(button)open(button.dataset.id)};search.oninput=renderList;document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==search){e.preventDefault();search.focus()}if(e.key==='Escape'&&current)close()});refresh();setInterval(refresh,1500);
})();
