(()=>{
const schedule='https://mpcsdiscord-production.up.railway.app/api/schedule',liveBase='https://mpcsdiscord-production.up.railway.app/api/live/';let timer=null,current=null;
const style=document.createElement('style');style.textContent=`
#matchList{gap:18px!important}.match.match-game{position:relative!important;grid-template-columns:140px minmax(180px,1fr) 90px minmax(180px,1fr) 116px!important;min-height:145px!important;padding:22px 24px!important;border:1px solid #223842!important;border-left:4px solid #00e5ff!important;background:linear-gradient(120deg,#0d1d24 0%,#09151a 60%,#0b1b21 100%)!important;box-shadow:0 10px 30px #0003;transition:transform .18s,border-color .18s,box-shadow .18s}.match.match-game:hover{transform:translateY(-3px);border-color:#00e5ff88!important;box-shadow:0 16px 42px #0007,0 0 24px #00e5ff12}.game-team{min-height:72px;padding:14px 17px;border:1px solid #1d333c;background:#071218;justify-content:center;transition:background .18s,border-color .18s}.game-team:hover{background:#0d242c;border-color:#00e5ff66}.game-center b{font-size:21px!important}.game-status{justify-self:center!important;border-radius:2px;background:#00e5ff0c}.watch-now{position:absolute;right:20px;bottom:17px;z-index:3;width:105px;padding:9px 8px;border:1px solid #00e5ff;background:#00e5ff;color:#041014;font:900 9px var(--body);letter-spacing:1.3px;cursor:pointer;clip-path:polygon(7px 0,100% 0,100% calc(100% - 7px),calc(100% - 7px) 100%,0 100%,0 7px);transition:transform .18s,box-shadow .18s}.watch-now:hover{transform:translateY(-2px);box-shadow:0 0 24px #00e5ff77}
.live-watch{position:fixed;inset:0;z-index:9999;display:none;place-items:center;padding:24px;background:#02080de8;backdrop-filter:blur(12px)}.live-watch.open{display:grid}.live-card{width:min(920px,100%);max-height:90vh;overflow:auto;border:1px solid #28505c;border-top:3px solid #00e5ff;background:linear-gradient(145deg,#0d1d24,#071116);box-shadow:0 25px 100px #000;padding:30px}.live-top{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #20343d;padding-bottom:18px}.live-top b{color:#ff405c;letter-spacing:2px}.live-top h3{margin:6px 0 0}.live-close{border:0;background:none;color:#fff;font-size:30px;cursor:pointer}.live-fighters{display:grid;grid-template-columns:1fr 110px 1fr;align-items:center;gap:25px;padding:38px 0}.live-player{text-align:center}.live-player h2{margin:0 0 12px;font:900 36px var(--head)}.live-hearts{color:#ff526c;font:800 27px var(--head)}.health-track{height:12px;margin:16px auto 0;max-width:290px;background:#18272d;overflow:hidden}.health-track i{display:block;height:100%;background:linear-gradient(90deg,#ff405c,#ff8a5c);transition:width .25s}.live-vs{text-align:center;color:#60757e;letter-spacing:1px}.live-vs b{display:block;margin-top:7px;color:#fff;font:900 27px var(--head)}.round-result{margin:-12px 0 25px;padding:14px;border:1px solid #00e5ff55;background:#00e5ff0b;text-align:center;color:#00e5ff;font:800 17px var(--head);letter-spacing:1px}.combat-log{max-height:240px;overflow:auto;border-top:1px solid #20343d;padding-top:16px}.combat-log p{display:flex;justify-content:space-between;gap:15px;margin:0;padding:11px;border-bottom:1px solid #17272e;color:#b8c5ca}.combat-log strong{color:#fff}.combat-log em{color:#ff6075;font-style:normal}.combat-log .round-event{color:#00e5ff;background:#00e5ff08}.combat-log .round-event strong{color:#00e5ff}
@media(max-width:760px){.match.match-game{grid-template-columns:1fr 55px 1fr!important;min-height:190px!important;padding:52px 14px 55px!important}.game-meta{position:absolute;left:15px;top:12px}.game-status{position:absolute;right:15px;top:12px}.watch-now{right:15px;bottom:12px}.game-team{padding:10px}.live-fighters{grid-template-columns:1fr}.live-vs{order:-1}.live-card{padding:18px}.combat-log p{display:block}.combat-log p span{display:block;margin-top:5px}}
`;document.head.append(style);
const modal=document.createElement('div');modal.className='live-watch';modal.innerHTML='<section class="live-card"><div class="live-top"><div><b>● LIVE</b><h3>SWORD MATCH</h3></div><button class="live-close" aria-label="Close">×</button></div><div id="liveContent"></div></section>';document.body.append(modal);modal.querySelector('.live-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};
function close(){modal.classList.remove('open');current=null;clearTimeout(timer)}function open(id){current=id;modal.classList.add('open');load()}function safe(v){const d=document.createElement('div');d.textContent=String(v??'TBD');return d.innerHTML}function hearts(v){return `${Number(v||0).toFixed(1)} ❤`}
function eventRow(e){if(e.type==='ROUND_WIN'||e.type==='MATCH_WIN')return `<p class="round-event"><span><strong>${safe(e.winner)}</strong> won ${e.type==='MATCH_WIN'?'the match':`round ${e.round}`}</span><span>${e.scoreOne} — ${e.scoreTwo}</span></p>`;return `<p><span><strong>${safe(e.attacker)}</strong> hit ${safe(e.target)}</span><span><em>-${Number(e.damage||0).toFixed(1)} ❤</em> · ${Number(e.remaining||0).toFixed(1)} left</span></p>`}
function render(data){const[a={name:'TBD',health:0,maxHealth:20},b={name:'TBD',health:0,maxHealth:20}]=data.players||[],events=data.events||[],lastWin=events.find(e=>e.type==='ROUND_WIN'||e.type==='MATCH_WIN');document.getElementById('liveContent').innerHTML=`<div class="live-fighters"><div class="live-player"><h2>${safe(a.name)}</h2><div class="live-hearts">${hearts(a.health)}</div><div class="health-track"><i style="width:${Math.max(0,Math.min(100,a.health/a.maxHealth*100))}%"></i></div></div><div class="live-vs"><span>ROUND ${data.round}</span><b>${data.scoreOne} — ${data.scoreTwo}</b></div><div class="live-player"><h2>${safe(b.name)}</h2><div class="live-hearts">${hearts(b.health)}</div><div class="health-track"><i style="width:${Math.max(0,Math.min(100,b.health/b.maxHealth*100))}%"></i></div></div></div>${lastWin?`<div class="round-result">${safe(lastWin.winner)} WON ${lastWin.type==='MATCH_WIN'?'THE MATCH':`ROUND ${lastWin.round}`}</div>`:''}<div class="combat-log"><h3>LIVE COMBAT FEED</h3>${events.length?events.map(eventRow).join(''):'<p>Waiting for the first hit…</p>'}</div>`}
function load(){if(!current)return;fetch(liveBase+encodeURIComponent(current),{cache:'no-store'}).then(r=>{if(!r.ok)throw 0;return r.json()}).then(render).catch(()=>{document.getElementById('liveContent').innerHTML='<div class="empty-state"><h2>ARENA PREPARING</h2><p>The live combat feed will appear when the Sword round starts.</p></div>'}).finally(()=>{if(current)timer=setTimeout(load,750)})}
function decorate(){fetch(schedule,{cache:'no-store'}).then(r=>r.json()).then(data=>{const live=(data.matches||[]).filter(m=>m.status==='LIVE'&&m.watchReady===true&&m.teamOneName&&m.teamTwoName);document.querySelectorAll('#matchList .match-game').forEach(card=>{const text=card.textContent.toLowerCase(),match=live.find(m=>text.includes(m.teamOneName.toLowerCase())&&text.includes(m.teamTwoName.toLowerCase())),old=card.querySelector('.watch-now');if(!match){old?.remove();return}if(old?.dataset.liveId===match.id)return;old?.remove();const button=document.createElement('button');button.className='watch-now';button.dataset.liveId=match.id;button.textContent='WATCH NOW';button.onclick=()=>open(match.id);card.append(button)})}).catch(()=>{})}decorate();setInterval(decorate,2000);
})();
